/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liveness + mode report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List conversations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationRead"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One conversation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationDetail"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Free-text trip request */
                        query: string;
                        /**
                         * Format: uuid
                         * @description Continue an existing conversation, or omit to start one
                         */
                        conversation_id?: string | null;
                        /**
                         * @description Stable id used to load/save preferences
                         * @default anonymous
                         */
                        user_id?: string;
                    };
                };
            };
            responses: {
                /** @description Plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            conversation_id: string;
                            thread_id: string;
                            /** @enum {string} */
                            status: "completed" | "blocked" | "awaiting_review";
                            blocked_reason?: string | null;
                            reasoning?: string | null;
                            /** @default [] */
                            selected_agents: ("flight" | "hotel" | "weather" | "budget" | "itinerary")[];
                            trip_constraints?: {
                                destination?: string | null;
                                origin?: string | null;
                                duration_days?: number | null;
                                start_date?: string | null;
                                travelers?: number | null;
                                budget?: number | null;
                                notes?: string | null;
                            } | null;
                            weather?: {
                                destination: string;
                                summary: string;
                                avg_high_c?: number | null;
                                avg_low_c?: number | null;
                                /** @default [] */
                                conditions: string[];
                            } | null;
                            /** @default [] */
                            flights: {
                                airline: string;
                                flight_number: string;
                                origin: string;
                                destination: string;
                                depart_time?: string | null;
                                price: number;
                                /** @default USD */
                                currency: string;
                                duration?: string | null;
                            }[];
                            /** @default [] */
                            hotels: {
                                name: string;
                                area?: string | null;
                                rating?: number | null;
                                price_per_night: number;
                                /** @default USD */
                                currency: string;
                                nights?: number | null;
                                total?: number | null;
                            }[];
                            budget?: {
                                /** @default USD */
                                currency: string;
                                flights_total?: number | null;
                                hotels_total?: number | null;
                                daily_estimate?: number | null;
                                grand_total?: number | null;
                                notes?: string | null;
                            } | null;
                            itinerary_plan?: string | null;
                            summary?: string | null;
                            /** @default [] */
                            memory_used: string[];
                            /** @default [] */
                            llm_calls: {
                                node: string;
                                model: string;
                                mocked: boolean;
                                prompt_tokens?: number | null;
                                completion_tokens?: number | null;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description The paused conversation to resume
                         */
                        conversation_id: string;
                        /**
                         * @description approve the itinerary or request changes
                         * @enum {string}
                         */
                        action: "approve" | "request_changes";
                        /** @description What to change (when request_changes) */
                        feedback?: string | null;
                    };
                };
            };
            responses: {
                /** @description Plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            conversation_id: string;
                            thread_id: string;
                            /** @enum {string} */
                            status: "completed" | "blocked" | "awaiting_review";
                            blocked_reason?: string | null;
                            reasoning?: string | null;
                            /** @default [] */
                            selected_agents: ("flight" | "hotel" | "weather" | "budget" | "itinerary")[];
                            trip_constraints?: {
                                destination?: string | null;
                                origin?: string | null;
                                duration_days?: number | null;
                                start_date?: string | null;
                                travelers?: number | null;
                                budget?: number | null;
                                notes?: string | null;
                            } | null;
                            weather?: {
                                destination: string;
                                summary: string;
                                avg_high_c?: number | null;
                                avg_low_c?: number | null;
                                /** @default [] */
                                conditions: string[];
                            } | null;
                            /** @default [] */
                            flights: {
                                airline: string;
                                flight_number: string;
                                origin: string;
                                destination: string;
                                depart_time?: string | null;
                                price: number;
                                /** @default USD */
                                currency: string;
                                duration?: string | null;
                            }[];
                            /** @default [] */
                            hotels: {
                                name: string;
                                area?: string | null;
                                rating?: number | null;
                                price_per_night: number;
                                /** @default USD */
                                currency: string;
                                nights?: number | null;
                                total?: number | null;
                            }[];
                            budget?: {
                                /** @default USD */
                                currency: string;
                                flights_total?: number | null;
                                hotels_total?: number | null;
                                daily_estimate?: number | null;
                                grand_total?: number | null;
                                notes?: string | null;
                            } | null;
                            itinerary_plan?: string | null;
                            summary?: string | null;
                            /** @default [] */
                            memory_used: string[];
                            /** @default [] */
                            llm_calls: {
                                node: string;
                                model: string;
                                mocked: boolean;
                                prompt_tokens?: number | null;
                                completion_tokens?: number | null;
                            }[];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail: string;
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            detail: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            env: string;
            /** @enum {string} */
            llm_mode: "live" | "mock";
            /** @enum {string} */
            langfuse: "enabled" | "disabled";
        };
        ConversationRead: {
            /** Format: uuid */
            id: string;
            thread_id: string;
            title?: string | null;
            created_at: string;
            updated_at: string;
        };
        ConversationDetail: components["schemas"]["ConversationRead"] & {
            /** @default [] */
            messages: components["schemas"]["MessageRead"][];
        };
        MessageRead: {
            /** Format: uuid */
            id: string;
            role: string;
            content: string;
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
