/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_plan_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BudgetAnalysis */
        BudgetAnalysis: {
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Flights Total */
            flights_total?: number | null;
            /** Hotels Total */
            hotels_total?: number | null;
            /** Daily Estimate */
            daily_estimate?: number | null;
            /** Grand Total */
            grand_total?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["MessageRead"][];
        };
        /** ConversationRead */
        ConversationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FlightOption */
        FlightOption: {
            /** Airline */
            airline: string;
            /** Flight Number */
            flight_number: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Depart Time */
            depart_time?: string | null;
            /** Price */
            price: number;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Duration */
            duration?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Env */
            env: string;
            /**
             * Llm Mode
             * @enum {string}
             */
            llm_mode: "live" | "mock";
            /**
             * Langfuse
             * @enum {string}
             */
            langfuse: "enabled" | "disabled";
        };
        /** HotelOption */
        HotelOption: {
            /** Name */
            name: string;
            /** Area */
            area?: string | null;
            /** Rating */
            rating?: number | null;
            /** Price Per Night */
            price_per_night: number;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Nights */
            nights?: number | null;
            /** Total */
            total?: number | null;
        };
        /** LLMCall */
        LLMCall: {
            /** Node */
            node: string;
            /** Model */
            model: string;
            /** Mocked */
            mocked: boolean;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
            /** Completion Tokens */
            completion_tokens?: number | null;
        };
        /** MessageRead */
        MessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Query
             * @description Free-text trip request
             */
            query: string;
            /**
             * Conversation Id
             * @description Continue an existing conversation, or omit to start one
             */
            conversation_id?: string | null;
        };
        /** PlanResponse */
        PlanResponse: {
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /** Thread Id */
            thread_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "blocked" | "awaiting_review";
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Reasoning */
            reasoning?: string | null;
            /** Selected Agents */
            selected_agents?: ("flight" | "hotel" | "weather" | "budget" | "itinerary")[];
            trip_constraints?: components["schemas"]["TripConstraints"] | null;
            weather?: components["schemas"]["WeatherInfo"] | null;
            /** Flights */
            flights?: components["schemas"]["FlightOption"][];
            /** Hotels */
            hotels?: components["schemas"]["HotelOption"][];
            budget?: components["schemas"]["BudgetAnalysis"] | null;
            /** Itinerary Plan */
            itinerary_plan?: string | null;
            /** Summary */
            summary?: string | null;
            /** Llm Calls */
            llm_calls?: components["schemas"]["LLMCall"][];
        };
        /** ResumeRequest */
        ResumeRequest: {
            /**
             * Conversation Id
             * Format: uuid
             * @description The paused conversation to resume
             */
            conversation_id: string;
            /**
             * Action
             * @description approve the itinerary or request changes
             * @enum {string}
             */
            action: "approve" | "request_changes";
            /**
             * Feedback
             * @description What to change (used when action is request_changes)
             */
            feedback?: string | null;
        };
        /** TripConstraints */
        TripConstraints: {
            /** Destination */
            destination?: string | null;
            /** Origin */
            origin?: string | null;
            /** Duration Days */
            duration_days?: number | null;
            /** Start Date */
            start_date?: string | null;
            /** Travelers */
            travelers?: number | null;
            /** Budget */
            budget?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeatherInfo */
        WeatherInfo: {
            /** Destination */
            destination: string;
            /** Summary */
            summary: string;
            /** Avg High C */
            avg_high_c?: number | null;
            /** Avg Low C */
            avg_low_c?: number | null;
            /** Conditions */
            conditions?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"][];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_plan_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
